### ISSUE TITLE
[BUG] truncated/ inconsistent text entry when using shimmering focus with Excalidraw

### ISSUE THREAD

**Issue by rushikb** [chrisgrieser/shimmering-focus#64] opened 2021-12-20 02:28 UTC
**Describe the Bug**
- text entry in excalidraw plugin when using shimmering focus gets truncated and makes is impossible to read/ write

**To Reproduce**
1. Create new excalidraw file 
2. type in any text

**Is the Problem related to Obsidian 0.13+ / Live Preview Mode?**
no

**Relevant Screenshots**
![CleanShot 2021-12-15 at 10 42 05](https://user-images.githubusercontent.com/6484525/146703207-4c800f12-9906-450f-9597-4b95acc69fc5.gif)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I checked that the issue does not occur when using the default theme.

**Comment by chrisgrieser** [comment] 2021-12-20 06:00
that is pretty weird since I do not change anything about how the Excalidraw plugin works...

I'll look into it what could cause this as a side effect.

**Comment by rushikb** [comment] 2021-12-21 00:38
I spoke to the creator of Excalidraw for his thoughts. His notes below
> This looks like a theme issue indeed. These type of things happen when a theme designer defines style of an HTML element (like probably textarea in this case), instead of scoping theme settings based on element class.You can look for textarea {} in the theme css somewhere, that is probably causing the issue

**Comment by chrisgrieser** [comment] 2021-12-21 12:34
ah, thanks for asking – that actually led me to the cause of the bug. Should be fixed now!

**Closed** 2021-12-21 12:33 UTC
Labels: bug
