### ISSUE TITLE
Text Indent Issue in obsidian-pandoc-reference-list

### ISSUE THREAD

**Issue by HeftyFair** [chrisgrieser/shimmering-focus#288] opened 2023-11-06 02:38 UTC
### Plugin

obsidian-pandoc-reference-list

### Issue

<img width="487" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/124026807/ca61227a-7c6a-46de-bf57-6a549c4ca96f">
 
the text in reference view (in obsidian-pandoc-reference-list) is not properly indended.
after I manually delete the text-indent,
<img width="472" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/124026807/5f23e21b-4f8d-45d1-ba0c-d1f3917f3a4e">
the text seems to be normal
<img width="489" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/124026807/f43fda16-257b-4cf8-b2db-71e6bdafc037">

default theme behavior:

<img width="473" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/124026807/dc7a399a-e415-4857-8e2d-0a275fe1918f">

### To reproduce

1. Install obsidian-pandoc-reference-list and shimmering-focus plugin
2. open reference tab by obsidian-pandoc-reference-list plugin

### Checklist

- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)

**Comment by chrisgrieser** [comment] 2023-11-06 11:11
Hmm, it looks fine on my end. 
![Pasted image 2023-11-06 at 12 08 42@2x](https://github.com/chrisgrieser/shimmering-focus/assets/73286100/13b19dd5-c9cf-4d3d-858a-d83db9cb247c)

also, the default theme shows me no such numbers:
![Pasted image 2023-11-06 at 12 09 07@2x](https://github.com/chrisgrieser/shimmering-focus/assets/73286100/d6702d9c-5deb-4024-9d3e-c4e6d251aa2d)

I assume you have a plugin or css snippet that somehow adds those numbers, since it's not Shimmering Focus that does that. Closing this, since this does not seem to be an issue caused by the theme

**Comment by HeftyFair** [comment] 2023-11-06 11:53
@chrisgrieser Thank you for your help! I find that the issue lies with the citation style — I was using the IEEE citation style, but after switching to the MLA (Modern Language Association 9th edition) format, the numbering disappeared.
<img width="316" alt="image" src="https://github.com/chrisgrieser/shimmering-focus/assets/124026807/effc8f0e-48a5-4ade-b0eb-c462c565f556">
I believe this is still an issue because users should have the flexibility to employ any citation style of their choosing.

**Comment by chrisgrieser** [comment] 2023-11-06 12:23
ah yes, with the citation style being the culprit, this makes sense to re-open, yes.

 However, I am not sure how to deal with this in a manner that does not break some citation style. 

@mgmeyers do you know how exactly the processed references are put out, so theme devs like me can implement styling of the references properly without some citation style breaking everything?

**Comment by chrisgrieser** [comment] 2024-03-19 11:06
Okay, I since it's not possible to ensure correct indentation, I just removed all the indentation alltogether, so it should look correctly with any citation style

**Closed by chrisgrieser** 2024-03-19 11:06 UTC
Labels: plugin support
