### ISSUE TITLE
[Bug]: Empty Space on the right

### ISSUE THREAD

**Issue by albfaggion** [chrisgrieser/shimmering-focus#164] opened 2022-05-04 18:11 UTC
### Bug Description

There is an empty space on the right side and a lack of space on the left side bar. 

### Relevant Screenshot

<img width="2240" alt="Screen Shot 2022-05-04 at 14 50 13" src="https://user-images.githubusercontent.com/87950446/166778840-c284f1ac-2f51-4787-aa76-cff62e8e0c1f.png">
<img width="2240" alt="Screen Shot 2022-05-04 at 14 50 45" src="https://user-images.githubusercontent.com/87950446/166778999-226c3233-e8a8-421a-9e86-d1f9cb5a9405.png">

### To Reproduce

Colapse the right and the left side to see the empty space on the right.
Show the left side bar to see some space lacking there.

### Obsidian Version

0.14.6

### Installer Version

0.14.6

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by imeed166** [comment] 2022-05-18 12:50
this is caused by `hider` plugin when you enable `hide app ribbon` in the plugin settings

**Comment by albfaggion** [comment] 2022-05-18 13:06
Oh, thank you!



---

andreafaggion.com

**Comment by imeed166** [comment] 2022-05-18 13:10
This theme doesn't need to support the plugin because It already has all the features the plugins provides. So you should probably close this issue.

**Closed** 2022-05-18 13:15 UTC
Labels: bug

**Comment by imeed166** [comment] 2022-05-18 14:27
np, had the exact same thing happened to me in the past
